name: Auto commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "0 7,8,9,10,11 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > today
          
      - name: Commit changes
        run: |
          git config --local user.name "vcyzteen"
          git config --local user.email "vcyzscape@gmail.com"
          git add -A
          
          arr[0]="GenA Auto Commit"
          arr[1]="GenB Auto Commit"
          arr[2]="GenC Auto Commit"
          arr[3]="GenD Auto Commit"
          arr[4]="GenE Auto Commit"
          arr[5]="GenF Auto Commit"
          arr[6]="GenG Auto Commit"
          arr[7]="GenH Auto Commit"
          arr[8]="GenI Auto Commit"
          arr[9]="GenJ Auto Commit"

          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
